### ISSUE TITLE
Ulm OTP: Homepage not available anymore 

### ISSUE THREAD

**Issue by 1Maxnet1** [public-transport/transport-apis#64]
https://github.com/public-transport/transport-apis/blob/236d88d00f3bbdfaf8b623a8556b9fae6a22cf61/data/de/ulm-otp.json#L5

I wanted to check out the available documentation for the Ulm OTP endpoint, but the homepage does not work anymore. Do you know an updated version? Is it known whether the endpoint is still available, although the homepage isn't ?

**Comment by derhuerst** [comment]
@robbi5 Is this due to the [ongoing dispute with the city of Ulm](https://verschwoerhaus.de/das-verschwörhaus-ist-ausgezogen-die-räume-am-weinhof-sind-nun-leer/)? If that is the case, we should remove the link or link to an explainer page.

**Comment by derhuerst** [comment]
I guess we should remove it from the list. We can bring the file back in case someone re-enables the endpoint.

**Comment by derhuerst** [comment]
Closing since https://github.com/public-transport/transport-apis/pull/67 is merged.
